### ISSUE TITLE
External Native Build Issues

### ISSUE THREAD

**Issue by Mo7mud** [sergeychilingaryan/AOSP-Kayboard-7.1.2#1]
Hello,
I'm getting this error when try to build the project

`Error while executing process D:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\AOSP-Kayboard-7.1.2\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=D:\AOSP-Kayboard-7.1.2\app\src\main\cpp\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/AOSP-Kayboard-7.1.2/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\AOSP-Kayboard-7.1.2\app\build\intermediates\ndkBuild\debug\lib APP_CPPFLAGS+="-std=c++11 -frtti -fexceptions" APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}`

`process_begin: CreateProcess(NULL, "", ...) failed.`

`make: rtti: No such file or directory`

`make: exceptions: No such file or directory`

`make: *** No rule to make target `exceptions'.  Stop.`

**Comment by bctpl** [comment]
libjni_latinimegoogle.so not working after change packagename
