### ISSUE TITLE
 make: rtti: No such file or directory make: exceptions: No such file or directory

### ISSUE THREAD

**Issue by Mo7mud** [sergeychilingaryan/AOSP-Kayboard-7.1.2#2]
I'm trying to build this project but it gives this error in Android studio:

```
process_begin: CreateProcess(NULL, "", ...) failed. 
make: rtti: No such file or directory 
make: exceptions: No such file or directory 
make: *** No rule to make target `exceptions'.  Stop.
```

I'm using latest version of NDK and Android Studio 3.1 Canary 8

**Comment by sergchil** [comment]
If you want only JAVA part, try to disable NDK build and use bundled so files instead

Sorry, but I'm not working on this project anymore :(

**Comment by Mo7mud** [comment]
Thank you very much

**Comment by sergchil** [comment]
@EgyptianM  welcome :)

**Comment by bhavdip99** [comment]
I am also facing this issue while I making project.
But If I remove this flag **rtti** and **exceptions**  Its make perfect build but I don't know if I remove this flag do get any issue?.

Thanks
Bhavdip

**Comment by sergchil** [comment]
It's safe to build without rtti and exceptions

**Comment by bhavdip99** [comment]
Thanks,
But may I get to know that why it is using this two flags?

share me some knowledgeable things if you can.
