### ISSUE TITLE
Native lib crash on android 8.x 9.0 device

### ISSUE THREAD

**Issue by TuanTuan** [sergeychilingaryan/AOSP-Kayboard-7.1.2#6]
The project works well on devices which under android 8.0, but the native lib always crash on android 8.x 9.0 device.

**Comment by mgood7123** [comment]
oh ;-;

**Comment by sergchil** [comment]
Sorry guys, I'm not supporting the project anymore :(

**Comment by bctpl** [comment]
> 
> 
> The project works well on devices which under android 8.0, but the native lib always crash on android 8.x 9.0 device.

Did you find solution?
